package org.example.userauthservice_may2026.services;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.jsonwebtoken.Claims;
import io.jsonwebtoken.JwtParser;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.MacAlgorithm;
import org.antlr.v4.runtime.misc.Pair;
import org.example.userauthservice_may2026.clients.KafkaProducerClient;
import org.example.userauthservice_may2026.dtos.EmailDto;
import org.example.userauthservice_may2026.exceptions.PasswordMismatchException;
import org.example.userauthservice_may2026.exceptions.UserAlreadyExistsException;
import org.example.userauthservice_may2026.exceptions.UserNotSignedUpException;
import org.example.userauthservice_may2026.models.Role;
import org.example.userauthservice_may2026.models.State;
import org.example.userauthservice_may2026.models.User;
import org.example.userauthservice_may2026.models.UserSession;
import org.example.userauthservice_may2026.repos.RoleRepo;
import org.example.userauthservice_may2026.repos.UserRepo;
import org.example.userauthservice_may2026.repos.UserSessionRepo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Service;

import javax.crypto.SecretKey;
import java.util.*;

@Service
public class AuthService {

    @Autowired
    private UserRepo userRepo;

    @Autowired
    private RoleRepo roleRepo;

    @Autowired
    private UserSessionRepo userSessionRepo;

    @Autowired
    private BCryptPasswordEncoder bCryptPasswordEncoder;

    @Autowired
    private SecretKey secretKey;

    @Autowired
    private KafkaProducerClient kafkaProducerClient;

    @Autowired
    private ObjectMapper objectMapper;

    public User signup(String name,String email,String password) {
        Optional<User> userOptional = userRepo.findByEmail(email);
        if (userOptional.isPresent()) {
           throw new UserAlreadyExistsException("Email already exists. Please use different email Id");
        }

        User user = new User();
        user.setEmail(email);
        user.setName(name);
       // user.setPassword(password); //hash this password
        user.setPassword(bCryptPasswordEncoder.encode(password));

        Role role = null;
        Optional<Role> roleOptional = roleRepo.findByValue("NON_ADMIN");
        if (roleOptional.isEmpty()) {
            role = new Role();
            role.setValue("NON_ADMIN");
            roleRepo.save(role);
        } else {
            role = roleOptional.get();
        }

        List<Role> roles = new ArrayList<>();
        roles.add(role);
        user.setRoles(roles);
        User savedUser = userRepo.save(user);

        ////////
        // Put a message into Kafka at this point
        EmailDto emailDto = new EmailDto();
        emailDto.setTo(email);
        emailDto.setFrom("anuragonhiring@gmail.com");
        emailDto.setSubject("Welcome to Scaler");
        emailDto.setBody("Have a good learning experience");
        try {
            String message = objectMapper.writeValueAsString(emailDto);
            kafkaProducerClient.sendMessage("signup", message);
        }catch (JsonProcessingException exception) {
            throw new RuntimeException("Something went bad");
        }

        ///////

        return savedUser;
    }

    public Pair<User,String> login(String email, String password) {
        Optional<User> userOptional = userRepo.findByEmail(email);
        if (userOptional.isEmpty() || userOptional.get().getState().equals(State.INACTIVE)) {
          throw new UserNotSignedUpException("Please signup first !!");
        }

        User user = userOptional.get();
      //  if (!user.getPassword().equals(password)) {
        if (!bCryptPasswordEncoder.matches(password,user.getPassword())) {
           throw new PasswordMismatchException("Passwords don't match");
        }

        //token generation on wed
        Map<String,Object>  claims = new HashMap<>();
        claims.put("user_id",user.getId());
        List<String> permissions = new ArrayList<>();
        for(Role role :user.getRoles()) {
            permissions.add(role.getValue());
        }
        claims.put("access",permissions);
        Long currentTime = System.currentTimeMillis();
        claims.put("iat",currentTime);
        claims.put("exp",currentTime+1000);

        String token = Jwts.builder().claims(claims).signWith(secretKey).compact();

        UserSession userSession = new UserSession();
        userSession.setToken(token);
        userSession.setUser(user);
        userSession.setState(State.ACTIVE);
        userSessionRepo.save(userSession);

        return new Pair<>(user,token);
    }


    public Boolean validateToken(String inputToken) {
        //generated by me
        //expired or not
       Optional<UserSession> optionalUserSession = userSessionRepo.findByToken(inputToken);
       if (optionalUserSession.isEmpty())  {
           System.out.println("Token doesn't exist");
           return false;
       }

       UserSession userSession = optionalUserSession.get();
        JwtParser jwtParser = Jwts.parser().verifyWith(secretKey).build();
        Claims claims = jwtParser.parseSignedClaims(inputToken).getPayload();
        Long expiryTime = (Long)claims.get("exp");
        Long currentTime = System.currentTimeMillis();
        System.out.println("expiry Time = " + expiryTime);
        System.out.println("current Time = "+ currentTime);
        if (currentTime > expiryTime) {
            System.out.println("Token is expired");
            //userSession.setState(State.INACTIVE);
            //userSessionRepo.save(userSession);
            userSessionRepo.deleteById(userSession.getId());
            return false;
        }

        return true;
    }
}

//signup
//pass = "anurag"
//bcrypt.encode("anurag") -> "AKAKAKA"
//
//login
//pass  = "anurag"
//bcrypt.encode("anurag") -> "BABABABA"

